[tool.poetry]
name = "stara-astar-nuitka"
version = "0.1.0"
description = ""
authors = ["Valerius Mattfeld <mail@valerius.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
stara-maze-generator = { git = "https://github.com/valerius21/Stara-Maze-Generator.git", branch = "numpy-2.1.3" }
nuitka = "^2.5.9"
numpy = "2.1.3"

# [tool.poetry.scripts]
# build_nuitka = "python -m nuitka --follow-imports --standalone --onefile ./stara_astar_nuitka/astar_nuitka.py"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
